[package]
name = "near-cli"
version = "0.1.0"
authors = ["FroVolod <frol_off@meta.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
dialoguer = "0.7"
# strum = "0.20"
strum = { git = "https://github.com/frol/strum", branch = "feat/discriminants-pass-through-attributes", features = ["derive"] }
strum_macros = "0.20"
smart-default = "0.6.0"
derive_more = "0.99.9"

async-recursion = "0.3.2"

actix = "0.11.0-beta.2"
actix-web = { version = "4.0.0-beta.3", features = [ "openssl" ] }
openssl-probe = { version = "0.1.2" }

base64 = "0.12.3"
bip39 = { version = "1.0.0", features = [ "rand" ] }
bs58 = "0.3"
ed25519-dalek = { version = "1" }
hex = "0.4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
dirs = "3.0"
# The fix is needed for seemless clap integration: https://github.com/wusyong/slip10/pull/3
slip10 = { git = "https://github.com/frol/slip10", rev = "159d5fd46a44b9251d0748ef1f343f908bf57a22" }
url = { version = "2", features = ["serde"] }
url_open = "0.0.1"

ledger-transport = "0.8.0"
ledger-transport-hid = "0.8.0"
ledger-apdu = "0.8.0"

color-eyre = "0.5"

near-crypto = { git = "https://github.com/near/nearcore", rev="9a7d172adeefcfd522723d741c2fa2d134392b8f" }
near-primitives = { git = "https://github.com/near/nearcore", rev="9a7d172adeefcfd522723d741c2fa2d134392b8f" }
near-jsonrpc-client = { git = "https://github.com/near/nearcore", rev="9a7d172adeefcfd522723d741c2fa2d134392b8f" }
near-jsonrpc-primitives = { git = "https://github.com/near/nearcore", rev="9a7d172adeefcfd522723d741c2fa2d134392b8f" }

hex-slice = "0.1.4"
